server:
  port: 5555
spring:
  application:
    name: platform-user
  jta:
    atomikos:
      properties:
        log-base-dir: /platform-user
#        log-base-name: platform-user
#  datasource:
#    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
  zipkin:  #java -jar zipkin-server-2.17.0-exec.jar --zipkin.collector.rabbitmq.addresses=localhost --zipkin.collector.rabbitmq.username=guest --zipkin.collector.rabbitmq.password=guest
    base-url: http://180.76.240.128:9411    # 指定了 zipkin 服务器的地址
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  rabbitmq:
    addresses: 180.76.240.128  #rabbitmq无法启动需要在容器内部执行rabbitmq-plugins enable rabbitmq_management命令
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:6666//user/info

logging:
  level:
    com:
      qxxg:
        springcloud: debug
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000

#配置断路器超时时间，默认是1000（1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000
#          strategy: SEMAPHORE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


mysql:
  datasource:
    size: 2
    write:
      jdbc-url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat
    read01:
      jdbc-url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat
    read02:
      jdbc-url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      minIdle: 5
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat