# Sample Logstash configuration for creating a simple
# Beats -> Logstash -> Elasticsearch pipeline.

input {
  rabbitmq{
    host=>"180.76.240.128"
    port=> 5672
    exchange=>'ex_logstash'
    exchange_type => "direct"
    user=>"guest"
    password=>"guest"
    queue=>"q_logstash"
    durable=> true
    #codec => plain{ charset => "UTF-8" }
     codec => json {
            charset => "UTF-8"
        }
    #type=> "all"
    key => "lgstash"
    auto_delete => false
    }
}
 
## Add your filters / logstash plugins configuration here
filter{
    json{
      source => "message"
      #target => "content"
    }
}
output {
  elasticsearch {
    hosts => "180.76.240.128:9200"
    index => "position-%{+YYYYMMdd}"
  }
  #stdout { codec => rubydebug }
}