server:
  port: 6666
spring:
  application:
    name: oauth-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
    password: root

#  zipkin:
#    base-url: http://180.76.240.128:9411    # 指定了 zipkin 服务器的地址
#    sender:
#      type: rabbit
#  sleuth:
#    sampler:
#      probability: 1.0    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#  rabbitmq:
#    addresses: 180.76.240.128


#  redis:
#    expireSeconds: 120
#    timeout: 20000
#    cluster:
#      nodes: 192.168.2.226:7010 ,192.168.2.226:7011, 192.168.2.227:7010, 192.168.2.227:7011, 192.168.2.228:7010, 192.168.2.228:7011
#      maxRedirects: 6
#    max-active: 8
#    min-idle: 0
#    max-idle: 8
#    max-wait: -1

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS