server:
  port: 7007
spring:
  application:
    name: platform-admin
  boot:
    admin:
      context-path: /admin
      ui:
        title: platform平台监控中心

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

