server:
  port: 7007
spring:
  application:
    name: platform-admin
  boot:
    admin:
      ui:
        title: platform平台监控中心
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span> platform平台监控中心</span>"
  security:
    user:
      name: abbot
      password: abbot

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

