server:
  port: 4444
spring:
  output:
    ansi:
      enabled: always
  application:
    name: platform-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/fallbackcontroller

  zipkin:
    base-url: http://180.76.240.128:9411    # 指定了 zipkin 服务器的地址
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  rabbitmq:
    addresses: 180.76.240.128


  redis:
    expireSeconds: 120
    timeout: 20000
    cluster:
      nodes: 192.168.2.226:7010 ,192.168.2.226:7011, 192.168.2.227:7010, 192.168.2.227:7011, 192.168.2.228:7010, 192.168.2.228:7011
      maxRedirects: 6
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    max-active: 8
    min-idle: 0
    #最大空闲数
    max-idle: 8
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    max-wait: -1

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
