server:
  port: 2221

spring:
  application:
    name: platform-log
  zipkin:
    base-url: http://180.76.240.128:9411    # 指定了 zipkin 服务器的地址
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0    # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  rabbitmq:
    addresses: 180.76.240.128
  jta:
    atomikos:
      properties:
        log-base-dir: /platform-log
  #      log-base-name: platform-log
#        log-base-dir: ./log/platform-log
#        enable-logging: false

eureka:
  client:
    service-url:
      defaultZone:  http://smallsand:smallsand@service1:7777/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS